driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  # https://hub.docker.com/_/centos/
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[haproxy]
    includes:
      - centos-7