driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  # https://hub.docker.com/_/centos/
  - name: centos-7.3
    driver_config:
      image: bento/centos-7.3

suites:
  - name: default
    run_list:
      - recipe[haproxy]
    includes:
      - centos-7.3