---
driver:
  name: dokken

transport:
  name: dokken

provisioner:
  name: dokken
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver:
      image: centos:7
      platform: rhel
      pid_one_command: /usr/lib/systemd/systemd

suites:
  - name: default
    run_list:
      - recipe[haproxy::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
