---
driver:
  name: dokken

transport:
  name: dokken

provisioner:
  name: dokken
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
#  - name: ubuntu-16.04
  - name: centos-7.3
    driver:
      image: centos:7
      platform: rhel
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install lsof which systemd-sysv initscripts wget net-tools

suites:
  - name: default
    run_list:
      - recipe[haproxy::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
