language: ruby

sudo: required

services:
  - docker

install:
  - bundle install

script:
  - bundle exec rake style
#  - bundle exec rake unit
#  - bundle exec kitchen test -d never

env:
  global:
    - KITCHEN_YAML=.kitchen.docker.yml