sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk
      
branches:
  only:
    - master

services: docker

env:
  matrix:
   - OS_INSTANCE=centos-7.3

script: KITCHEN_LOCAL_YAML=.kitchen.yml /opt/chefdk/embedded/bin/kitchen verify ${OS_INSTANCE}

notifications:
  email:
    - joseph@yourcgi.com
